// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Festival struct {
	ID               pgtype.UUID        `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	DateType         string             `json:"date_type"`
	UsualMonth       pgtype.Text        `json:"usual_month"`
	Date2026Start    pgtype.Date        `json:"date_2026_start"`
	Date2026End      pgtype.Date        `json:"date_2026_end"`
	Region           string             `json:"region"`
	HeritageType     string             `json:"heritage_type"`
	FestivalType     string             `json:"festival_type"`
	Summary          string             `json:"summary"`
	Story            pgtype.Text        `json:"story"`
	WhatToExpect     pgtype.Text        `json:"what_to_expect"`
	HowToParticipate pgtype.Text        `json:"how_to_participate"`
	PracticalInfo    pgtype.Text        `json:"practical_info"`
	CoverImageUrl    pgtype.Text        `json:"cover_image_url"`
	GalleryImages    []byte             `json:"gallery_images"`
	VideoEmbeds      []byte             `json:"video_embeds"`
	IsPublished      pgtype.Bool        `json:"is_published"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Memory struct {
	ID           pgtype.UUID        `json:"id"`
	FestivalID   pgtype.UUID        `json:"festival_id"`
	AuthorName   pgtype.Text        `json:"author_name"`
	AuthorEmail  pgtype.Text        `json:"author_email"`
	Content      string             `json:"content"`
	YearOfMemory pgtype.Text        `json:"year_of_memory"`
	Status       pgtype.Text        `json:"status"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
}

type Subscription struct {
	ID                pgtype.UUID        `json:"id"`
	Email             string             `json:"email"`
	DigestWeekly      pgtype.Bool        `json:"digest_weekly"`
	FestivalReminders []byte             `json:"festival_reminders"`
	Confirmed         pgtype.Bool        `json:"confirmed"`
	ConfirmationToken pgtype.Text        `json:"confirmation_token"`
	UnsubscribeToken  string             `json:"unsubscribe_token"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
