// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmSubscription = `-- name: ConfirmSubscription :exec
UPDATE subscriptions
SET confirmed = true, confirmation_token = NULL
WHERE id = $1
`

func (q *Queries) ConfirmSubscription(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, confirmSubscription, id)
	return err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    email, digest_weekly, festival_reminders, confirmation_token, unsubscribe_token
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, email, digest_weekly, festival_reminders, confirmed, confirmation_token, unsubscribe_token, created_at
`

type CreateSubscriptionParams struct {
	Email             string      `json:"email"`
	DigestWeekly      pgtype.Bool `json:"digest_weekly"`
	FestivalReminders []byte      `json:"festival_reminders"`
	ConfirmationToken pgtype.Text `json:"confirmation_token"`
	UnsubscribeToken  string      `json:"unsubscribe_token"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.Email,
		arg.DigestWeekly,
		arg.FestivalReminders,
		arg.ConfirmationToken,
		arg.UnsubscribeToken,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DigestWeekly,
		&i.FestivalReminders,
		&i.Confirmed,
		&i.ConfirmationToken,
		&i.UnsubscribeToken,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getSubscriptionByConfirmationToken = `-- name: GetSubscriptionByConfirmationToken :one
SELECT id, email, digest_weekly, festival_reminders, confirmed, confirmation_token, unsubscribe_token, created_at FROM subscriptions
WHERE confirmation_token = $1
`

func (q *Queries) GetSubscriptionByConfirmationToken(ctx context.Context, confirmationToken pgtype.Text) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByConfirmationToken, confirmationToken)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DigestWeekly,
		&i.FestivalReminders,
		&i.Confirmed,
		&i.ConfirmationToken,
		&i.UnsubscribeToken,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByEmail = `-- name: GetSubscriptionByEmail :one
SELECT id, email, digest_weekly, festival_reminders, confirmed, confirmation_token, unsubscribe_token, created_at FROM subscriptions
WHERE email = $1
`

func (q *Queries) GetSubscriptionByEmail(ctx context.Context, email string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByEmail, email)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DigestWeekly,
		&i.FestivalReminders,
		&i.Confirmed,
		&i.ConfirmationToken,
		&i.UnsubscribeToken,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByUnsubscribeToken = `-- name: GetSubscriptionByUnsubscribeToken :one
SELECT id, email, digest_weekly, festival_reminders, confirmed, confirmation_token, unsubscribe_token, created_at FROM subscriptions
WHERE unsubscribe_token = $1
`

func (q *Queries) GetSubscriptionByUnsubscribeToken(ctx context.Context, unsubscribeToken string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUnsubscribeToken, unsubscribeToken)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DigestWeekly,
		&i.FestivalReminders,
		&i.Confirmed,
		&i.ConfirmationToken,
		&i.UnsubscribeToken,
		&i.CreatedAt,
	)
	return i, err
}

const listConfirmedWeeklyDigest = `-- name: ListConfirmedWeeklyDigest :many
SELECT id, email, digest_weekly, festival_reminders, confirmed, confirmation_token, unsubscribe_token, created_at FROM subscriptions
WHERE confirmed = true AND digest_weekly = true
`

func (q *Queries) ListConfirmedWeeklyDigest(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listConfirmedWeeklyDigest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DigestWeekly,
			&i.FestivalReminders,
			&i.Confirmed,
			&i.ConfirmationToken,
			&i.UnsubscribeToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
